CREATE TABLE INCIDENT
(
    ID INT PRIMARY KEY  AUTO_INCREMENT UNIQUE,
    INCIDENT_DATE /*DATETIME*/ VARCHAR(255) NOT NULL,
    INCIDENT_CATEGORY VARCHAR(255) NOT NULL,
    INCIDENT_PRIORITY VARCHAR(20) NOT NULL,
    REQUESTER_DEPARTMENT VARCHAR(255) NOT NULL,
    REQUESTER VARCHAR(255) NOT NULL,
    REQUESTER_CONTACTS VARCHAR(255) NOT NULL,
    IP_ADDRESS VARCHAR(16),
    INCIDENT_DURATION INT,
    INCIDENT_DESCRIPTION VARCHAR(255),
    EXECUTOR VARCHAR(255),
    OPERATOR VARCHAR(255) NOT NULL,
    INCIDENT_STATUS VARCHAR(20) NOT NULL,
    INCIDENT_CLOSEDATA DATETIME
)