create table inm.category
(
    id        integer not null
        primary key,
    parent_id integer not null,
    title     varchar(255)
);

alter table inm.category
    owner to oto;

create table inm.department
(
    code        integer not null
        primary key,
    active      boolean,
    parent_code integer not null,
    short_title varchar(255),
    title       varchar(255)
);

alter table inm.department
    owner to oto;

create table inm.faq
(
    id          integer not null
        primary key,
    card_text   text,
    card_title  varchar(255),
    category_id integer
        constraint fkfk218m39poixxbo7bibctxa67
        references inm.category
);

alter table inm.faq
    owner to oto;

create table inm.priority
(
    id          integer not null
        primary key,
    description varchar(255),
    term        integer not null
);

alter table inm.priority
    owner to oto;

create table inm.roles
(
    id   integer not null
        primary key,
    name varchar(255)
);

alter table inm.roles
    owner to oto;

create table inm.status
(
    id    integer not null
        primary key,
    done  boolean not null,
    title varchar(255)
);

alter table inm.status
    owner to oto;

create table inm.users
(
    id       integer generated by default as identity
        primary key,
    contacts varchar(255),
    email    varchar(255),
    name     varchar(255),
    password varchar(255),
    username varchar(255)
        constraint uk_r43af9ap4edm43mmtq01oddj6
        unique,
    role_id  integer
        constraint fkp56c1712k691lhsyewcssf40f
        references inm.roles
);

alter table inm.users
    owner to oto;

create table inm.incident
(
    id                  integer not null
        primary key,
    closedate           timestamp,
    description         text,
    ipaddress           varchar(255),
    journal             varchar(255),
    opendate            timestamp,
    requester           varchar(255),
    requestercontacts   varchar(255),
    category_id         integer
        constraint fkcsiofvrmp929qa3p851yu2k3v
        references inm.category,
    engineer            integer
        constraint fkicsr4p6jn8smrso8atg1r5xra
        references inm.users,
    operator            integer
        constraint fkhx4hhyp7gese0bhcolk66p62x
        references inm.users,
    priority            integer default 1
        constraint fkk9pwjinekfl2k9y54l5axe1w3
        references inm.priority,
    requesterdepartment integer
        constraint fkkkfnkf7acwmh5al89fet7xpx7
        references inm.department,
    status              integer default 1
        constraint fkbuqqo1bqrmjjel8oh498af63x
        references inm.status
);

alter table inm.incident
    owner to oto;
