INSERT INTO INM.INCIDENT (ID, DATE, CATEGORY, PRIORITY, REQUESTER_DEPARTMENT, REQUESTER, REQUESTER_CONTACTS, IP_ADDRESS,
                          DURATION, DESCRIPTION, ENGINEER, OPERATOR, STATUS, CLOSE_DATE, JOURNAL)
VALUES (1, '2020-07-05 18:22:26', 1, 1, 1, ' Дмитрий Юрьевич', '182', '10.89.1.159', 5, 'Что то не работает', 1, 1, 1,
        null, null);