INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (1, '1 отдел УГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (2, '2 отдел УГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (3, '3 отдел УГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (4, '4 отдел УГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (5, '5 отдел УГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (6, '6 отдел УГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (7, '7 отдел УГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (8, '8 отдел УГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (9, '9 отдел УГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (10, '10 отдел УГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (11, '11 отдел УГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (12, 'ЦАФАП ГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (13, 'РОИО ГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (14, 'ЦТУДТ ГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (15, 'МРЭО ГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (16, 'МРЭО ГИБДД № 1');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (17, 'МРЭО ГИБДД № 2');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (18, 'МРЭО ГИБДД № 3');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (19, 'МРЭО ГИБДД № 4');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (20, 'МРЭО ГИБДД № 5');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (21, 'МРЭО ГИБДД № 6');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (22, 'МОТНиРАС ГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (23, 'МРЭО ГИБДД № 8');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (24, 'МРЭО ГИБДД № 9');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (25, 'МРЭО ГИБДД № 10');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (26, 'МРЭО ГИБДД № 11');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (27, 'МРЭО ГИБДД № 12');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (28, 'МРЭО ГИБДД № 13');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (29, 'МРЭО ГИБДД № 14');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (30, 'МРЭО ГИБДД № 15');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (31, 'МРЭО ГИБДД № 16');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (32, 'МРЭО ГИБДД № 17');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (33, 'МРЭО ГИБДД № 18');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (34, 'ОСБ ДПС ГИБДД');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (35, 'ОБ ДПС ГИБДД № 1');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (36, 'ОБ ДПС ГИБДД № 2');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (37, 'ОБ ДПС ГИБДД № 3');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (38, 'ОБ ДПС ГИБДД № 4');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (39, 'ОБ ДПС ГИБДД № 5');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (40, 'ОР ДПС ГИБДД № 1');
INSERT INTO INM.DEPARTMENT (ID, TITLE)
VALUES (41, 'ОР ДПС ГИБДД № 2');