INSERT INTO INM.USERS_GROUP (ID, NAME)
VALUES (1, 'root');
INSERT INTO INM.USERS_GROUP (ID, NAME)
VALUES (2, 'administrator');
INSERT INTO INM.USERS_GROUP (ID, NAME)
VALUES (3, 'engineer');
INSERT INTO INM.USERS_GROUP (ID, NAME)
VALUES (4, 'programmer');
INSERT INTO INM.USERS_GROUP (ID, NAME)
VALUES (5, 'securityEngineer');