INSERT INTO INM.CATEGORY (ID, LEVEL, LEFT_KEY, RIGHT_KEY, TITLE, PARENT_ID)
VALUES (1, 1, 1, 24, 'CATEGORY', 0);
INSERT INTO INM.CATEGORY (ID, LEVEL, LEFT_KEY, RIGHT_KEY, TITLE, PARENT_ID)
VALUES (2, 2, 2, 7, 'PC', 1);
INSERT INTO INM.CATEGORY (ID, LEVEL, LEFT_KEY, RIGHT_KEY, TITLE, PARENT_ID)
VALUES (3, 2, 8, 13, 'NETWORK', 1);
INSERT INTO INM.CATEGORY (ID, LEVEL, LEFT_KEY, RIGHT_KEY, TITLE, PARENT_ID)
VALUES (4, 2, 14, 23, 'SERVICES', 1);
INSERT INTO INM.CATEGORY (ID, LEVEL, LEFT_KEY, RIGHT_KEY, TITLE, PARENT_ID)
VALUES (5, 3, 3, 4, 'HARDWARE', 2);
INSERT INTO INM.CATEGORY (ID, LEVEL, LEFT_KEY, RIGHT_KEY, TITLE, PARENT_ID)
VALUES (6, 3, 5, 6, 'SOFTWARE', 2);
INSERT INTO INM.CATEGORY (ID, LEVEL, LEFT_KEY, RIGHT_KEY, TITLE, PARENT_ID)
VALUES (7, 3, 9, 10, 'NETWORK-CARD', 3);
INSERT INTO INM.CATEGORY (ID, LEVEL, LEFT_KEY, RIGHT_KEY, TITLE, PARENT_ID)
VALUES (8, 3, 11, 12, 'CABLE', 3);
INSERT INTO INM.CATEGORY (ID, LEVEL, LEFT_KEY, RIGHT_KEY, TITLE, PARENT_ID)
VALUES (9, 3, 15, 16, 'FIS-M', 4);
INSERT INTO INM.CATEGORY (ID, LEVEL, LEFT_KEY, RIGHT_KEY, TITLE, PARENT_ID)
VALUES (10, 3, 17, 18, 'SED', 4);
INSERT INTO INM.CATEGORY (ID, LEVEL, LEFT_KEY, RIGHT_KEY, TITLE, PARENT_ID)
VALUES (11, 3, 19, 20, 'SEP', 4);
INSERT INTO INM.CATEGORY (ID, LEVEL, LEFT_KEY, RIGHT_KEY, TITLE, PARENT_ID)
VALUES (12, 3, 21, 22, 'SUDIS', 4);