INSERT INTO inm.priority (ID, INFLUENCE, URGENCY, DESCRIPTION, TERM) VALUES (1, 1, 1, 'Critical', 1);
INSERT INTO inm.priority (ID, INFLUENCE, URGENCY, DESCRIPTION, TERM) VALUES (2, 1, 2, 'Hight', 8);
INSERT INTO inm.priority (ID, INFLUENCE, URGENCY, DESCRIPTION, TERM) VALUES (3, 2, 2, 'Medium', 24);
INSERT INTO inm.priority (ID, INFLUENCE, URGENCY, DESCRIPTION, TERM) VALUES (4, 2, 3, 'Low', 48);
INSERT INTO inm.priority (ID, INFLUENCE, URGENCY, DESCRIPTION, TERM) VALUES (5, 3, 3, 'Plane', 2160);